default: &default
  adapter:  postgresql
  encoding: unicode
  pool:     5
  # migrations_paths: ../../../db/migrate

development:
  <<: *default
  database: api_session_recovering_app_development

test:
  <<: *default
  database: api_session_recovering_app_test
